{% set name = "xwrf" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xwrf-{{ version }}.tar.gz
  sha256: 88456783df035e6c5d07f60d402f382663e20b2c808417bcdf9461d07fddf8be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - donfig >=0.6.0
    - pyproj >=2.4.1
    - python >=3.7
    - xarray >=0.18,!=0.20.0,!=0.20.1

test:
  imports:
    - xwrf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://xwrf.readthedocs.io
  summary: A lightweight interface for working with the Weather Research and Forecasting (WRF) model output in Xarray.
  dev_url: https://github.com/xarray-contrib/xwrf
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jthielen
    - lpilz
    - kmpaul
